apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-server
  namespace: lab-storage
spec:
  selector:
    matchLabels:
      app: create-storage
  replicas: 1 
  template:
    metadata:
      labels:
        app: create-storage
    spec:
      containers:
      - name: httpd-24-rhel7
        image: registry.access.redhat.com/ubi8/httpd-24:latest
        ports:
        - containerPort: 80
        volumeMounts:
            - name: apache-root-dir
              mountPath: /var/www/html
      volumes:
      - name: apache-root-dir
        persistentVolumeClaim:
          claimName: pvc-finance
