kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-finance
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /public/finance
    server: upi-0.montse1.lab.psi.pnq2.redhat.com
  persistentVolumeReclaimPolicy: Recycle 
