apiVersion: v1
kind: Service
metadata:
  name: apache-server
  namespace: lab-storage
spec:
  selector:
    app: create-storage
  type: NodePort
  ports:
    - port: 80
      nodePort: 32000
      targetPort: 80
