apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-storage-role-binding
  namespace: lab-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: argocd-cluster-argocd-application-controller
  namespace: openshift-gitops

