apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: create-storage
  namespace: openshift-gitops
spec:
  destination:
    namespace: lab-storage
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: nfs2
    repoURL: https://github.com/montseAF/reproductions.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
